arb-dir: lib/core/localizations/arb
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localizations/gen/l10n
nullable-getter: false
preferred-supported-locales: ["en", "es", "fr", "de", "ja", "bn"]
use-deferred-loading: false